<?xml version='1.0'?>

<robot name="cart_front_steer" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find robot)/urdf/robot.gazebo" />

  <xacro:property name="wheel_radius" value="0.0275" />
  <xacro:property name="wheel_width" value="0.025" />
  <xacro:property name="footprint_width"  value="0.9" />
  <xacro:property name="footprint_height"  value="0.2" />
  <xacro:property name="footprint_length" value="1.0" />
  <xacro:property name="axel_dx" value="0.4" />

  <link name="robot_footprint"></link>


  <joint name="robot_footprint_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="robot_footprint"/>
    <child link="chassis" />
  </joint>


  <link name='chassis'>
    <inertial>
      <mass value="10.0"/>
      <origin xyz="${-footprint_length/2 + axel_dx} 0 0" rpy=" 0 0 0"/>
      <inertia
          ixx="0.001" ixy="0" ixz="0"
          iyy="0.001" iyz="0"
          izz="0.001"
      />
    </inertial>

    <collision name='chassis_collision'>
      <origin xyz="${-footprint_length/2 + axel_dx} 0 ${wheel_radius}" rpy=" 0 0 0"/>
      <geometry>
        <box size="${footprint_length} ${footprint_width} ${footprint_height}"/>
      </geometry>
    </collision>

    <visual name='chassis_visual'>
      <origin xyz="${-footprint_length/2 + axel_dx} 0 ${wheel_radius}" rpy=" 0 0 0"/>
      <geometry>
        <box size="${footprint_length} ${footprint_width} ${footprint_height}"/>
      </geometry>
    </visual>

  </link>


  <link name="front_left_wheel">
    <collision name='front_left_wheel_collision'>
      <origin xyz="0 ${wheel_width/2} 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>0</mu>
            <mu2>0</mu2>
            <slip1>1.0</slip1>
            <slip2>1.0</slip2>
          </ode>
        </friction>
      </surface>
    </collision>

    <visual name='front_left_wheel_visual'>
      <origin xyz="0 ${wheel_width/2} 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1"/>
      <origin xyz="0.0 0 0" rpy="0 1.5707 1.5707"/>
      <inertia
          ixx="0.0001" ixy="0" ixz="0"
          iyy="0.0001" iyz="0"
          izz="0.003"
      />
    </inertial>
  </link>

  <link name="front_right_wheel">
    <collision name='front_right_wheel_collision'>
      <origin xyz="0 ${-wheel_width/2} 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <surface>
      <friction>
        <ode>
          <mu>0</mu>
          <mu2>0</mu2>
          <slip1>1.0</slip1>
          <slip2>1.0</slip2>
        </ode>
      </friction>
    </surface>
    <visual name='front_right_wheel_visual'>
      <origin xyz="0 ${-wheel_width/2} 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1"/>
      <origin xyz="0.0 0 0" rpy="0 1.5707 1.5707"/>
      <inertia
          ixx="0.0001" ixy="0" ixz="0"
          iyy="0.0001" iyz="0"
          izz="0.003"
      />
    </inertial>
  </link>

  <link name="back_left_wheel">
    <collision name='back_left_wheel_collision'>
      <origin xyz="0 ${wheel_width/2} 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>0</mu>
            <mu2>0</mu2>
            <slip1>1.0</slip1>
            <slip2>1.0</slip2>
          </ode>
        </friction>
      </surface>
    </collision>

    <visual name='back_left_wheel_visual'>
      <origin xyz="0 ${wheel_width/2} 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1"/>
      <origin xyz="0.0 0 0" rpy="0 1.5707 1.5707"/>
      <inertia
          ixx="0.0001" ixy="0" ixz="0"
          iyy="0.0001" iyz="0"
          izz="0.003"
      />
    </inertial>
  </link>

  <link name="back_right_wheel">
    <collision name='back_right_wheel_collision'>
      <origin xyz="0 ${-wheel_width/2} 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <surface>
      <friction>
        <ode>
          <mu>0</mu>
          <mu2>0</mu2>
          <slip1>1.0</slip1>
          <slip2>1.0</slip2>
        </ode>
      </friction>
    </surface>
    <visual name='back_right_wheel_visual'>
      <origin xyz="0 ${-wheel_width/2} 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1"/>
      <origin xyz="0.0 0 0" rpy="0 1.5707 1.5707"/>
      <inertia
          ixx="0.0001" ixy="0" ixz="0"
          iyy="0.0001" iyz="0"
          izz="0.003"
      />
    </inertial>
  </link>

  <joint type="universal" name="front_left_wheel_hinge">
    <origin xyz="0 ${footprint_width/2 + 0.001} ${wheel_radius}" rpy="0 0 0"/>
    <child link="front_left_wheel"/>
    <parent link="chassis"/>
    <!--axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="1000" velocity="1000"/>
    <dynamics damping="0.0" friction="0.0"/-->
  </joint>

  <joint type="universal" name="front_right_wheel_hinge">
    <origin xyz="0 ${-footprint_width/2 - 0.001} ${wheel_radius}" rpy="0 0 0"/>
    <child link="front_right_wheel"/>
    <parent link="chassis"/>
    <!--axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="1000" velocity="1000"/>
    <dynamics damping="0.0" friction="0.0"/-->
  </joint>

  <joint type="revolute" name="back_left_wheel_hinge">
    <origin xyz="0 ${footprint_width/2 + 0.001} ${wheel_radius}" rpy="0 0 0"/>
    <child link="back_left_wheel"/>
    <parent link="chassis"/>
    <!--axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="1000" velocity="1000"/>
    <dynamics damping="0.0" friction="0.0"/-->
  </joint>

  <joint type="revolute" name="back_right_wheel_hinge">
    <origin xyz="0 ${-footprint_width/2 - 0.001} ${wheel_radius}" rpy="0 0 0"/>
    <child link="back_right_wheel"/>
    <parent link="chassis"/>
    <!--axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="1000" velocity="1000"/>
    <dynamics damping="0.0" friction="0.0"/-->
  </joint>

  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="back_left_wheel_hinge">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="back_right_wheel_hinge">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>



<gazebo reference="front_left_wheel">
    <material>Gazebo/Black</material>
</gazebo>

<gazebo reference="front_right_wheel">
    <material>Gazebo/Black</material>
</gazebo>

<gazebo reference="back_left_wheel">
    <material>Gazebo/Black</material>
</gazebo>

<gazebo reference="back_right_wheel">
    <material>Gazebo/Black</material>
</gazebo>

<gazebo reference="chassis">
    <material>Gazebo/Grey</material>
</gazebo>


</robot>
